// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Infrastructure.Context;

#nullable disable

namespace Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231001062648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Domain.Entities.Item.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c44a0000-647a-e86a-38eb-08dbc2476425"),
                            CreatedAt = new DateTime(2023, 10, 1, 9, 26, 48, 168, DateTimeKind.Local).AddTicks(4730),
                            Description = "Apple Iphone newest product",
                            Name = "Iphone14",
                            Price = 900m,
                            UpdatedAt = new DateTime(2023, 10, 1, 9, 26, 48, 168, DateTimeKind.Local).AddTicks(4771)
                        },
                        new
                        {
                            Id = new Guid("c44a0000-647a-e86a-3925-08dbc2476425"),
                            CreatedAt = new DateTime(2023, 10, 1, 9, 26, 48, 168, DateTimeKind.Local).AddTicks(4774),
                            Description = "Andriod Mobile phone",
                            Name = "Andriod",
                            Price = 800m,
                            UpdatedAt = new DateTime(2023, 10, 1, 9, 26, 48, 168, DateTimeKind.Local).AddTicks(4776)
                        },
                        new
                        {
                            Id = new Guid("c44a0000-647a-e86a-392c-08dbc2476425"),
                            CreatedAt = new DateTime(2023, 10, 1, 9, 26, 48, 168, DateTimeKind.Local).AddTicks(4781),
                            Description = "Dell Laptop",
                            Name = "Laptop",
                            Price = 700m,
                            UpdatedAt = new DateTime(2023, 10, 1, 9, 26, 48, 168, DateTimeKind.Local).AddTicks(4782)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
