// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Infrastructure.Context;

#nullable disable

namespace Shop.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230927144237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shop.Domain.Entities.Item.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08160000-647a-e86a-fee6-08dbbf67fe82"),
                            CreatedAt = new DateTime(2023, 9, 27, 17, 42, 37, 559, DateTimeKind.Local).AddTicks(1669),
                            Description = "Apple Iphone newest product",
                            Name = "Iphone14",
                            Price = 900m,
                            Quantity = 2,
                            UpdatedAt = new DateTime(2023, 9, 27, 17, 42, 37, 559, DateTimeKind.Local).AddTicks(1700)
                        },
                        new
                        {
                            Id = new Guid("08160000-647a-e86a-ff16-08dbbf67fe82"),
                            CreatedAt = new DateTime(2023, 9, 27, 17, 42, 37, 559, DateTimeKind.Local).AddTicks(1704),
                            Description = "Andriod Mobile phone",
                            Name = "Andriod",
                            Price = 800m,
                            Quantity = 5,
                            UpdatedAt = new DateTime(2023, 9, 27, 17, 42, 37, 559, DateTimeKind.Local).AddTicks(1705)
                        },
                        new
                        {
                            Id = new Guid("08160000-647a-e86a-ff1b-08dbbf67fe82"),
                            CreatedAt = new DateTime(2023, 9, 27, 17, 42, 37, 559, DateTimeKind.Local).AddTicks(1708),
                            Description = "Dell Laptop",
                            Name = "Laptop",
                            Price = 700m,
                            Quantity = 6,
                            UpdatedAt = new DateTime(2023, 9, 27, 17, 42, 37, 559, DateTimeKind.Local).AddTicks(1710)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
